export enum SymbolType {
  TITLE1 = 'TITLE1',
  TITLE2 = 'TITLE2',
  TITLE3 = 'TITLE3',
  TITLE4 = 'TITLE4',
  OPEN_PARENTHESES = 'OPEN_PARENTHESES',
  CLOSE_PARENTHESES = 'CLOSE_PARENTHESES',
  OPEN_SQUARE_BRACKETS = 'OPEN_SQUARE_BRACKETS',
  CLOSE_SQUARE_BRACKETS = 'CLOSE_SQUARE_BRACKETS',
  CODE_DELIMITER = 'CODE_DELIMITER',
  BOLD_DELIMITER = 'BOLD_DELIMITER',
  ITALIC_DELIMITER = 'ITALIC_DELIMITER',
  IMAGE = 'IMAGE',
  STRING = 'STRING',
  TEXT = 'TEXT',
  NEW_LINE = 'NEW_LINE',
  EOF = 'EOF',

  //TCC_CONFIG
  TITLE_TCC_CONFIG = 'TITLE_TCC_CONFIG',
  AUTHOR = 'AUTHOR',
  COURSE = 'COURSE',
  TCC_TITLE = 'TCC_TITLE',
  TCC_DATE = 'TCC_DATE',
  KEYWORD1 = 'KEYWORD1',
  KEYWORD2 = 'KEYWORD2',
  ADVISOR = 'ADVISOR',
  CO_ADVISOR = 'CO_ADVISOR',
  CATALOG_SHEET = 'CATALOG_SHEET',
  APPROVAL_DATE = 'APPROVAL_DATE',
  GUEST_MEMBER1 = 'GUEST_MEMBER1',
  GUEST_MEMBER2 = 'GUEST_MEMBER2',
  LOCAL = 'LOCAL',
  INSTITUTION = 'INSTITUTION',
  ABSTRACT_KEYWORD1 = 'ABSTRACT_KEYWORD1',
  ABSTRACT_KEYWORD2 = 'ABSTRACT_KEYWORD2',
  ABSTRACT_KEYWORD3 = 'ABSTRACT_KEYWORD3',
  RESUMO_KEYWORD1 = 'RESUMO_KEYWORD1',
  RESUMO_KEYWORD2 = 'RESUMO_KEYWORD2',
  RESUMO_KEYWORD3 = 'RESUMO_KEYWORD3',

  //RESUME
  TITLE_RESUME = 'TITLE_RESUME',

  //ABSTRACT
  TITLE_ABSTRACT = 'TITLE_ABSTRACT',

  //INTRODUCTION
  TITLE_INTRODUCTION = 'TITLE_INTRODUCTION',

  //APPENDIX
  TITLE_APPENDIX = 'TITLE_APPENDIX',

  //ATTACHMENTS
  TITLE_ATTACHMENTS = 'TITLE_ATTACHMENTS',
}
